# Yahoo Finance
# Source: https://github.com/Alex2Yang97/yahoo-finance-mcp
# Toolathlon Version: https://github.com/lockon-n/yahoo-finance-mcp
# Toolathlon_GYM: ../../local_servers/yahoo-finance-mcp
type: stdio
name: yahoo-finance
params:
  command: uv
  args:
    - "run"
    - "server.py"
  cwd: "${local_servers_paths}/yahoo-finance-mcp"
client_session_timeout_seconds: 60
cache_tools_list: true